### PR TITLE
FIX Tokyo Olympic

### PR DESCRIPTION
**Pull request by Peranikov**
"海の日", "体育の日" and "山の日" will move for the opening ceremony and closing ceremony of Tokyo Olympic. This bill was passed.
see: https://www3.nhk.or.jp/news/html/20180613/k10011476131000.html

### CODE REVIEW

**Comment by Peranikov** [comment]
Sorry, I'll fix test

**Comment by Peranikov** [comment]
I noticed it now, should I wait for this update?
https://github.com/holiday-jp/holiday_jp

**Comment by k1LoW** [comment]
@Peranikov Thank you for your commit !! 
https://github.com/holiday-jp/holiday_jp updated !!

**Comment by Peranikov** [comment]
@k1LoW thank you for your information! by the way, Are you planning to fix this?

> 具体的には、「海の日」を7月23日（開会式前日）、「体育の日」を7月24日（開会式）、「山の日」を8月10日（閉会式翌日）に持ってくるとしている。
http://www.itmedia.co.jp/business/articles/1806/13/news116.html

https://github.com/holiday-jp/holiday_jp-ruby/blob/master/holidays.yml#L785

**Comment by Peranikov** [comment]
Oh sorry, I checked fixed it.

https://github.com/holiday-jp/holiday_jp/blob/master/holidays.yml#L787

**Comment by k1LoW** [comment]
@Peranikov 

Could use https://github.com/holiday-jp/holiday_jp/releases/tag/v0.10.0 ?

Because holiday_jp-ruby does not yet support v1.x.

https://github.com/holiday-jp/holiday_jp#implemantations

**Comment by Peranikov** [comment]
I tried `bundle exec rake` with `master`, it seems to have failed.

```
Failure: test_yaml(TestHolidayJpYaml)
/projects/holiday_jp-ruby/test/test_holiday_jp_yaml.rb:10:in `block in test_yaml'
      7:     yaml = YAML.load_file(File.expand_path('../../holidays.yml', __FILE__))
      8:     holiday_jp_yaml = YAML.load_file(File.expand_path('../holiday_jp/holidays.yml', __FILE__))
      9:     yaml.map do |date, name|
  => 10:       assert_equal holiday_jp_yaml[date], name
     11:     end
     12:     holiday_jp_yaml.map do |date, name|
     13:       assert_equal yaml[date], name
/projects/holiday_jp-ruby/test/test_holiday_jp_yaml.rb:9:in `each'
/projects/holiday_jp-ruby/test/test_holiday_jp_yaml.rb:9:in `map'
/projects/holiday_jp-ruby/test/test_holiday_jp_yaml.rb:9:in `test_yaml'
<"天皇誕生日 振替休日"> expected but was
<"振替休日">

diff:
? 天皇誕生日 振替休日
```

**Comment by k1LoW** [comment]
> I tried bundle exec rake with master, it seems to have failed.

Yes. Because [holiday-jp/holiday_jp master branch](https://github.com/holiday-jp/holiday_jp) holidays.yml is 1.x. holiday_jp-ruby does not yet support v1.x.

Could you use submodule holiday_jp [v0.x](https://github.com/holiday-jp/holiday_jp/tree/v0.x) ?

**Comment by Peranikov** [comment]
@k1LoW Thank you, I understood! and I've fixed it.
Please review this PR.

**Comment by Peranikov** [comment]
@k1LoW Thank you for your support!

**Comment by komagata** [comment]
🎉

**Pull request merged**
