### PR TITLE
Adds support for Ruby 3.1

### PR DESCRIPTION
**Pull request by hosht**
Ruby 3.1 ships with Psych 4.0.3 which makes `YAML.load_file` defaults to safe mode (ruby/psych#487).
This causes error on parsing `holidays.yml`.

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @hosht. Thank you for your commitment!

I've modified the CI to run on pull requests. Could you merge the latest master branch?

**Comment by hosht** [comment]
master branch merged.

**Comment by k1LoW** [comment]
Thank you!!!

**Comment by k1LoW** [comment]
@komagata 
Since Ruby 3.1 has already been released, I think it's okay to release a Ruby 3.1 supported version of holiday_jp.gem.

**Comment by komagata** [comment]
@k1LoW I think so too.

**Comment by k1LoW** [comment]
@komagata 
If you are ok, could you release a new version of the gem? (I don't have the authority to do that.)

**Comment by komagata** [comment]
@k1LoW Thank you for your comment.
I push ver [0.8.1](https://rubygems.org/gems/holiday_jp/versions/0.8.1)

**Pull request merged**
