### PR TITLE
Use holiday-jp/holiday_jp v0.12.2 holidays.yml

### PR DESCRIPTION
**Pull request by k1LoW**
- Use holiday-jp/holiday_jp v0.12.2 holidays.yml
- Fix test ( 2021/8/21 is not "Mountain day")

### CODE REVIEW

**Review by komagata — APPROVED** [review]
Thank you. Looks good!

**Comment by k1LoW** [comment]
@komagata Thank for your review!

We're looking forward to the release of gem!!

**Comment by komagata** [comment]
@k1LoW Relese now!

https://rubygems.org/gems/holiday_jp/versions/0.8.0

**Comment by k1LoW** [comment]
Thank you!!!!!!!

**Pull request merged**
