### PR TITLE
Fix The Emperor's Birthday of 2018

### PR DESCRIPTION
**Pull request by Ryosuke0307**
Looking at the government page, the Emperor 's Birthday of 2018 is still December 23 
the same as 2017.
see: http://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

### CODE REVIEW

**Comment by Ryosuke0307** [comment]
Probably, era name will change at the beginning of 2019.
http://mainichi.jp/articles/20170111/k00/00m/010/101000c

**Comment by komagata** [comment]
Thanks for your PR.
But it is under consideration now.
Let's change the code if it becomes the official law.

**Comment by Ryosuke0307** [comment]
Thank you for your reply.

>Let's change the code if it becomes the official law.
 I agree with you.

**Comment by matsubo** [comment]
+1

This PR should be merged ASAP. Holidays in 2018 have been officially defined on Feb 2017 by Japanese law.

**Comment by komagata** [comment]
@matsubo I think that It is under consideration yet in japanese law.
http://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

If you know tell me law information by url.

**Comment by nyaago** [comment]
@komagata 

2017/11/13 現在の以下の内閣府のリンクの記述からすると、2018は12/23 日が天皇誕生日といういうことで決まっていると考えてよいのでこの PR がマージされるのが適切だとおもいます。

http://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

**Comment by komagata** [comment]
@nyaago Thank you for you infroamtion.

**Comment by miyucy** [comment]
Hi, We facing same problem. Why not push to rubygems? or Do you have any plan for release?

**Pull request merged**
