### PR TITLE
Add holidays related emperors enthoronment

### PR DESCRIPTION
**Pull request by u16suzu**
Hi,

I added some holidays related emperors enthoronment.
The holidays's evidence is here : https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @u16suzu 

Could you use holiday-jp/holiday_jp in https://github.com/holiday-jp/holiday_jp-ruby/tree/master/test as testcase ?

**Comment by u16suzu** [comment]
Hi @k1LoW 

The point is, I should add same holiday data to holiday-jp/holiday_jp?

**Comment by k1LoW** [comment]
@komagata Could you check this PR ? Looks good to me 👍

**Comment by komagata** [comment]
@u16suzu @k1LoW CI seems to have failed.

**Comment by u16suzu** [comment]
@komagata @k1LoW 
Yup, in some ruby versions bundler's installing for CI testing fails, 
though I fixed in some older ruby versions.
I will fix them. Would you like to wait?

**Comment by u16suzu** [comment]
@komagata @k1LoW 

Finally, I succeeded fixing the CI test. 😄 
For the following reasons, I locked bundler version which used at CI. 🔒 

- latest bundler 2.x, which installed via `gem update bundler`, only support ruby >= 2.3.0
- `holiday_jp.gemspec` specifies bundler version ~> 1.6

**Comment by komagata** [comment]
@u16suzu Thank you for your commits.

**Pull request merged**
